services:
  - type: web
    name: cotisation-pro
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build && npm install --prefix backend
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MYSQL_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://cotisation-pro.onrender.com
      - key: PORT
        value: 3000
